name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Setup railway
        run: npm i -g @railway/cli

      - name: debug
        run: RAILWAY_TOKEN=${{ secrets.RAILWAY_TOKEN }} railway run printenv

      - name: Install
        run: yarn

      - name: Lint
        run: yarn rw lint

      - name: Check
        run: yarn rw check

      - name: Test
        run: RAILWAY_TOKEN=${{ secrets.RAILWAY_TOKEN }} railway run TEST_DATABASE_URL=$DATABASE_URL yarn rw test --no-watch --no-db-push

      - name: Build
        run: yarn rw build

